apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
  labels:
    app: muchtodo-backend
type: Opaque
# Mongo URI base64 encoded:
# echo -n 'mongodb://admin:secret@mongodb-service:27017/muchtodo?authSource=admin' | base64
data:
  mongo-uri: bW9uZ29kYjovL2FkbWluOnNlY3JldEBtb25nb2RiLXNlcnZpY2U6MjcwMTcvbXVjaHRvZG8/YXV0aFNvdXJjZT1hZG1pbg==
